# some of the below taken from
# https://github.com/soft-matter/trackpy/commit/0a5c7e091f58bb899b57d58554b1202926f7a836
language: python
python:
  - "2.7"
  - "3.5"
# use miniconda for packages, in particular for numpy/scipy, see
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
# Append the conda-forge channel, instead of adding it. See:
# https://github.com/conda-forge/conda-forge.github.io/issues/232)
  - conda config --append channels conda-forge
  - conda create -n testenv --yes numpy scipy matplotlib pytest pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install
script: pytest
